language: node_js
node_js:
  - 12
install:
  - yarn install
script:
  - yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  target_branch: 'gh-pages'
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master